server {
    listen 80;
    server_name alexmchugh.dev;
    root /usr/share/nginx/html;
    index index.html;

    location / {
        try_files $uri $uri.html $uri/ /index.html;
    }

    location /cv.pdf {
        alias /usr/share/nginx/html/cv.pdf;
    }

    error_page 404 /404.html;
}
