apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: dfx
resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
images:
  - name: ghcr.io/alexmchugh1/alexmchugh-dev
    newTag: latest
