apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: alexmchugh-dev
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
images:
- name: ghcr.io/alexmchugh1/alexmchugh-dev
  newName: ghcr.io/alexmchugh1/alexmchugh-dev
  newTag: sha-bc0b6e1
